export type DeliveryTier = 1 | 2 | 3 | 4;

export type DeliveryCity = {
  slug: string;
  name: string;
  province: string;
  provinceSlug: string;
  deliveryDays: string;
  tier: DeliveryTier;
  nearbyAreas: string[];
  /** Extra unique copy for SEO — major cities only */
  localNote?: string;
  seoKeywords: string[];
};

export const PROVINCES = [
  { slug: "punjab", name: "Punjab" },
  { slug: "sindh", name: "Sindh" },
  { slug: "khyber-pakhtunkhwa", name: "Khyber Pakhtunkhwa" },
  { slug: "balochistan", name: "Balochistan" },
  { slug: "islamabad", name: "Islamabad Capital Territory" },
  { slug: "gilgit-baltistan", name: "Gilgit-Baltistan" },
  { slug: "azad-kashmir", name: "Azad Jammu & Kashmir" },
] as const;

export const deliveryCities: DeliveryCity[] = [
  // —— Punjab (ship-from Okara hub) ——
  {
    slug: "okara",
    name: "Okara",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "1 day (same-day dispatch)",
    tier: 1,
    nearbyAreas: ["Renala Khurd", "Depalpur", "Hujra Shah Muqeem", "Basirpur"],
    localNote:
      "Pure Herbex Ultra Force is packed and dispatched from our Okara facility. Local customers often receive orders within 24 hours with free Cash on Delivery.",
    seoKeywords: ["herbal stamina Okara", "Pure Herbex Okara", "sex timing medicine Okara COD"],
  },
  {
    slug: "lahore",
    name: "Lahore",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "1–2 business days",
    tier: 1,
    nearbyAreas: ["Model Town", "DHA Lahore", "Gulberg", "Johar Town", "Cantt", "Wagah"],
    localNote:
      "Lahore is our highest-volume delivery corridor from Okara. Orders via WhatsApp reach most Lahore zones in 24–48 hours in plain, unmarked packaging.",
    seoKeywords: ["herbal stamina Lahore", "timing medicine Lahore COD", "Pure Herbex Lahore delivery"],
  },
  {
    slug: "karachi",
    name: "Karachi",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "2–3 business days",
    tier: 1,
    nearbyAreas: ["Clifton", "DHA Karachi", "Gulshan", "North Nazimabad", "Malir", "Korangi"],
    localNote:
      "Karachi customers receive discreet COD parcels via trusted courier partners. We serve all major towns from Saddar to Scheme 33 with no advance payment required.",
    seoKeywords: ["herbal capsules Karachi", "sex enhancement Karachi COD", "Pure Herbex Karachi"],
  },
  {
    slug: "islamabad",
    name: "Islamabad",
    province: "Islamabad Capital Territory",
    provinceSlug: "islamabad",
    deliveryDays: "1–2 business days",
    tier: 1,
    nearbyAreas: ["F-6", "F-7", "G-11", "I-8", "Bahria Town Islamabad", "DHA Islamabad"],
    localNote:
      "Islamabad and twin-city Rawalpindi orders share a fast northern route from our Punjab warehouse with full privacy packaging.",
    seoKeywords: ["men health supplements Islamabad", "herbal stamina Islamabad COD", "Pure Herbex Islamabad"],
  },
  {
    slug: "rawalpindi",
    name: "Rawalpindi",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "1–2 business days",
    tier: 1,
    nearbyAreas: ["Saddar", "Satellite Town", "Westridge", "Chaklala", "Peshawar Road"],
    localNote:
      "Rawalpindi deliveries are coordinated with Islamabad routes for 24–48 hour arrival across cantonment and civilian sectors.",
    seoKeywords: ["herbal timing Rawalpindi", "Pure Herbex Rawalpindi", "stamina medicine Rawalpindi COD"],
  },
  {
    slug: "faisalabad",
    name: "Faisalabad",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2 business days",
    tier: 1,
    nearbyAreas: ["D Ground", "Susan Road", "Jaranwala Road", "Samundri", "Chiniot"],
    seoKeywords: ["herbal medicine Faisalabad", "Pure Herbex Faisalabad delivery", "stamina capsules Faisalabad"],
  },
  {
    slug: "multan",
    name: "Multan",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 1,
    nearbyAreas: ["Cantt", "Gulgasht", "Shah Rukn-e-Alam", "Lodhran", "Khanewal"],
    seoKeywords: ["herbal stamina Multan", "sex timing Multan COD", "Pure Herbex Multan"],
  },
  {
    slug: "gujranwala",
    name: "Gujranwala",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2 business days",
    tier: 1,
    nearbyAreas: ["Model Town", "Civil Lines", "Wapda Town", "Gujrat", "Sialkot"],
    seoKeywords: ["Pure Herbex Gujranwala", "herbal enhancement Gujranwala", "COD Gujranwala"],
  },
  {
    slug: "sialkot",
    name: "Sialkot",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Cantt", "Ugoki", "Daska", "Pasrur", "Wazirabad"],
    seoKeywords: ["herbal stamina Sialkot", "Pure Herbex Sialkot delivery", "timing medicine Sialkot"],
  },
  {
    slug: "sargodha",
    name: "Sargodha",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Satellite Town", "Khushab", "Bhalwal", "Sahiwal", "Mianwali"],
    seoKeywords: ["Pure Herbex Sargodha", "herbal capsules Sargodha COD"],
  },
  {
    slug: "bahawalpur",
    name: "Bahawalpur",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Model Town", "Cantt", "Ahmadpur East", "Hasilpur", "Khairpur Tamewali"],
    seoKeywords: ["herbal stamina Bahawalpur", "Pure Herbex Bahawalpur", "COD Bahawalpur"],
  },
  {
    slug: "sheikhupura",
    name: "Sheikhupura",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "1–2 business days",
    tier: 1,
    nearbyAreas: ["Ferozewala", "Muridke", "Sharaqpur", "Nankana Sahib"],
    seoKeywords: ["Pure Herbex Sheikhupura", "herbal medicine Sheikhupura COD"],
  },
  {
    slug: "kasur",
    name: "Kasur",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "1–2 business days",
    tier: 1,
    nearbyAreas: ["Pattoki", "Chunian", "Khudian", "Raiwind"],
    seoKeywords: ["herbal stamina Kasur", "Pure Herbex Kasur delivery"],
  },
  {
    slug: "gujrat",
    name: "Gujrat",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Lalamusa", "Kharian", "Sarai Alamgir", "Jalalpur Jattan"],
    seoKeywords: ["Pure Herbex Gujrat", "timing capsules Gujrat COD"],
  },
  {
    slug: "jhelum",
    name: "Jhelum",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Cantt", "Pind Dadan Khan", "Sohawa", "Dina"],
    seoKeywords: ["herbal enhancement Jhelum", "Pure Herbex Jhelum"],
  },
  {
    slug: "sahiwal",
    name: "Sahiwal",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "1–2 business days",
    tier: 1,
    nearbyAreas: ["Harappa", "Chichawatni", "Pakpattan", "Kamalia"],
    seoKeywords: ["Pure Herbex Sahiwal", "herbal stamina Sahiwal COD"],
  },
  {
    slug: "pakpattan",
    name: "Pakpattan",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2 business days",
    tier: 2,
    nearbyAreas: ["Arifwala", "Qaboola", "Sahiwal", "Depalpur"],
    seoKeywords: ["herbal medicine Pakpattan", "Pure Herbex Pakpattan"],
  },
  {
    slug: "vehari",
    name: "Vehari",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Burewala", "Mailsi", "Hasilpur", "Khanewal"],
    seoKeywords: ["Pure Herbex Vehari", "stamina capsules Vehari"],
  },
  {
    slug: "khanewal",
    name: "Khanewal",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Mian Channu", "Kabirwala", "Multan", "Lodhran"],
    seoKeywords: ["herbal timing Khanewal", "Pure Herbex Khanewal COD"],
  },
  {
    slug: "lodhran",
    name: "Lodhran",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Dunyapur", "Kahror Pakka", "Multan", "Bahawalpur"],
    seoKeywords: ["Pure Herbex Lodhran", "herbal stamina Lodhran"],
  },
  {
    slug: "bahawalnagar",
    name: "Bahawalnagar",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Fort Abbas", "Haroonabad", "Chishtian", "Minchinabad"],
    seoKeywords: ["herbal medicine Bahawalnagar", "Pure Herbex Bahawalnagar"],
  },
  {
    slug: "rahim-yar-khan",
    name: "Rahim Yar Khan",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Sadiqabad", "Khanpur", "Liaquatpur", "Zahir Pir"],
    seoKeywords: ["Pure Herbex Rahim Yar Khan", "COD Rahim Yar Khan herbal"],
  },
  {
    slug: "dera-ghazi-khan",
    name: "Dera Ghazi Khan",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Taunsa", "Kot Addu", "Muzaffargarh", "Layyah"],
    seoKeywords: ["herbal stamina DG Khan", "Pure Herbex Dera Ghazi Khan"],
  },
  {
    slug: "layyah",
    name: "Layyah",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Karor Lal Esan", "Chobara", "Bhakkar", "Muzaffargarh"],
    seoKeywords: ["Pure Herbex Layyah", "herbal capsules Layyah COD"],
  },
  {
    slug: "mianwali",
    name: "Mianwali",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Piplan", "Kundian", "Bhakkar", "Dera Ismail Khan"],
    seoKeywords: ["herbal medicine Mianwali", "Pure Herbex Mianwali"],
  },
  {
    slug: "bhakkar",
    name: "Bhakkar",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Darya Khan", "Mankera", "Khansar", "Layyah"],
    seoKeywords: ["Pure Herbex Bhakkar", "stamina Bhakkar delivery"],
  },
  {
    slug: "khushab",
    name: "Khushab",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Jauharabad", "Noorpur Thal", "Sargodha", "Mianwali"],
    seoKeywords: ["herbal stamina Khushab", "Pure Herbex Khushab"],
  },
  {
    slug: "narowal",
    name: "Narowal",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Shakargarh", "Zafarwal", "Sialkot", "Pasrur"],
    seoKeywords: ["Pure Herbex Narowal", "COD Narowal herbal"],
  },
  {
    slug: "hafizabad",
    name: "Hafizabad",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Pindi Bhattian", "Gujranwala", "Chiniot", "Sangla Hill"],
    seoKeywords: ["herbal enhancement Hafizabad", "Pure Herbex Hafizabad"],
  },
  {
    slug: "mandi-bahauddin",
    name: "Mandi Bahauddin",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Phalia", "Malakwal", "Gujrat", "Sargodha"],
    seoKeywords: ["Pure Herbex Mandi Bahauddin", "herbal medicine Mandi Bahauddin"],
  },
  {
    slug: "chiniot",
    name: "Chiniot",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Lalian", "Bhawana", "Faisalabad", "Jhang"],
    seoKeywords: ["herbal stamina Chiniot", "Pure Herbex Chiniot COD"],
  },
  {
    slug: "toba-tek-singh",
    name: "Toba Tek Singh",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Gojra", "Kamalia", "Pirmahal", "Jhang"],
    seoKeywords: ["Pure Herbex Toba Tek Singh", "timing medicine TTS"],
  },
  {
    slug: "nankana-sahib",
    name: "Nankana Sahib",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "1–2 business days",
    tier: 1,
    nearbyAreas: ["Sangla Hill", "Shahkot", "Sheikhupura", "Warburton"],
    seoKeywords: ["herbal capsules Nankana Sahib", "Pure Herbex Nankana Sahib"],
  },
  {
    slug: "attock",
    name: "Attock",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Hazro", "Fateh Jang", "Jand", "Wah Cantt"],
    seoKeywords: ["Pure Herbex Attock", "herbal stamina Attock COD"],
  },
  {
    slug: "chakwal",
    name: "Chakwal",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Talagang", "Kallar Kahar", "Choa Saidan Shah", "Jhelum"],
    seoKeywords: ["herbal medicine Chakwal", "Pure Herbex Chakwal"],
  },
  {
    slug: "murree",
    name: "Murree",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Ghora Gali", "Ayubia", "Rawalpindi", "Islamabad"],
    seoKeywords: ["Pure Herbex Murree delivery", "herbal stamina Murree"],
  },
  {
    slug: "wah-cantt",
    name: "Wah Cantt",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "1–2 business days",
    tier: 1,
    nearbyAreas: ["Taxila", "Hassan Abdal", "Rawalpindi", "Attock"],
    seoKeywords: ["Pure Herbex Wah Cantt", "herbal COD Wah Cantt"],
  },
  {
    slug: "jhang",
    name: "Jhang",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Shorkot", "Ahmadpur Sial", "Toba Tek Singh", "Chiniot"],
    seoKeywords: ["herbal stamina Jhang", "Pure Herbex Jhang"],
  },
  {
    slug: "muzaffargarh",
    name: "Muzaffargarh",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Kot Addu", "Alipur", "Jatoi", "Multan"],
    seoKeywords: ["Pure Herbex Muzaffargarh", "timing medicine Muzaffargarh"],
  },
  {
    slug: "kot-addu",
    name: "Kot Addu",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Taunsa", "Layyah", "Muzaffargarh", "DG Khan"],
    seoKeywords: ["herbal capsules Kot Addu", "Pure Herbex Kot Addu"],
  },
  {
    slug: "kamoke",
    name: "Kamoke",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2 business days",
    tier: 2,
    nearbyAreas: ["Gujranwala", "Muridke", "Eminabad", "Ghakhar"],
    seoKeywords: ["Pure Herbex Kamoke", "herbal delivery Kamoke"],
  },
  {
    slug: "daska",
    name: "Daska",
    province: "Punjab",
    provinceSlug: "punjab",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Sialkot", "Pasrur", "Wazirabad", "Gujranwala"],
    seoKeywords: ["herbal stamina Daska", "Pure Herbex Daska COD"],
  },

  // —— Sindh ——
  {
    slug: "hyderabad",
    name: "Hyderabad",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Latifabad", "Qasimabad", "Tando Jam", "Matiari"],
    localNote:
      "Hyderabad serves as our main Sindh hub after Karachi, with reliable COD courier coverage across Latifabad and Qasimabad.",
    seoKeywords: ["herbal stamina Hyderabad Sindh", "Pure Herbex Hyderabad", "COD Hyderabad"],
  },
  {
    slug: "sukkur",
    name: "Sukkur",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Rohri", "Pano Aqil", "Shikarpur", "Khairpur"],
    seoKeywords: ["Pure Herbex Sukkur", "herbal medicine Sukkur COD"],
  },
  {
    slug: "larkana",
    name: "Larkana",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Ratodero", "Dokri", "Shahdadkot", "Kamber"],
    seoKeywords: ["herbal capsules Larkana", "Pure Herbex Larkana"],
  },
  {
    slug: "mirpur-khas",
    name: "Mirpur Khas",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Umerkot", "Digri", "Hala", "Nawabshah"],
    seoKeywords: ["Pure Herbex Mirpur Khas", "stamina Mirpur Khas delivery"],
  },
  {
    slug: "nawabshah",
    name: "Nawabshah",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Sakrand", "Daur", "Sanghar", "Moro"],
    seoKeywords: ["herbal timing Nawabshah", "Pure Herbex Nawabshah"],
  },
  {
    slug: "jacobabad",
    name: "Jacobabad",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "4 business days",
    tier: 3,
    nearbyAreas: ["Thul", "Garhi Khairo", "Shikarpur", "Larkana"],
    seoKeywords: ["Pure Herbex Jacobabad", "herbal COD Jacobabad"],
  },
  {
    slug: "shikarpur",
    name: "Shikarpur",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Lakhi", "Khanpur", "Sukkur", "Jacobabad"],
    seoKeywords: ["herbal medicine Shikarpur", "Pure Herbex Shikarpur"],
  },
  {
    slug: "khairpur",
    name: "Khairpur",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Kot Diji", "Ranipur", "Sukkur", "Nawabshah"],
    seoKeywords: ["Pure Herbex Khairpur", "stamina Khairpur COD"],
  },
  {
    slug: "thatta",
    name: "Thatta",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Makli", "Gharo", "Sujawal", "Karachi"],
    seoKeywords: ["herbal delivery Thatta", "Pure Herbex Thatta"],
  },
  {
    slug: "badin",
    name: "Badin",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "4 business days",
    tier: 3,
    nearbyAreas: ["Tando Bago", "Matli", "Tando Adam", "Hyderabad"],
    seoKeywords: ["Pure Herbex Badin", "herbal capsules Badin"],
  },
  {
    slug: "sanghar",
    name: "Sanghar",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Shahdadpur", "Sinjhoro", "Nawabshah", "Mirpur Khas"],
    seoKeywords: ["herbal stamina Sanghar", "Pure Herbex Sanghar"],
  },
  {
    slug: "umerkot",
    name: "Umerkot",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "4 business days",
    tier: 3,
    nearbyAreas: ["Samaro", "Kunri", "Mirpur Khas", "Tharparkar"],
    seoKeywords: ["Pure Herbex Umerkot", "COD Umerkot herbal"],
  },
  {
    slug: "tharparkar",
    name: "Mithi (Tharparkar)",
    province: "Sindh",
    provinceSlug: "sindh",
    deliveryDays: "4–5 business days",
    tier: 3,
    nearbyAreas: ["Islamkot", "Chachro", "Diplo", "Umerkot"],
    seoKeywords: ["herbal delivery Tharparkar", "Pure Herbex Mithi"],
  },

  // —— Khyber Pakhtunkhwa ——
  {
    slug: "peshawar",
    name: "Peshawar",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["University Town", "Hayatabad", "Charsadda", "Nowshera"],
    localNote:
      "Peshawar orders are routed through our northern courier network with the same discreet packaging standard used nationwide.",
    seoKeywords: ["herbal stamina Peshawar", "Pure Herbex Peshawar COD", "timing medicine Peshawar"],
  },
  {
    slug: "mardan",
    name: "Mardan",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Takht Bhai", "Katlang", "Swabi", "Charsadda"],
    seoKeywords: ["Pure Herbex Mardan", "herbal capsules Mardan"],
  },
  {
    slug: "abbottabad",
    name: "Abbottabad",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Havelian", "Mansehra", "Haripur", "Murree"],
    seoKeywords: ["herbal medicine Abbottabad", "Pure Herbex Abbottabad delivery"],
  },
  {
    slug: "mingora-swat",
    name: "Mingora (Swat)",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "3–4 business days",
    tier: 3,
    nearbyAreas: ["Saidu Sharif", "Barikot", "Matta", "Bahrain"],
    seoKeywords: ["Pure Herbex Swat", "herbal stamina Mingora"],
  },
  {
    slug: "kohat",
    name: "Kohat",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Hangu", "Lachi", "Peshawar", "Bannu"],
    seoKeywords: ["herbal timing Kohat", "Pure Herbex Kohat COD"],
  },
  {
    slug: "bannu",
    name: "Bannu",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "3–4 business days",
    tier: 3,
    nearbyAreas: ["Lakki Marwat", "Domel", "Kohat", "Dera Ismail Khan"],
    seoKeywords: ["Pure Herbex Bannu", "stamina medicine Bannu"],
  },
  {
    slug: "mansehra",
    name: "Mansehra",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Baffa", "Oghi", "Abbottabad", "Balakot"],
    seoKeywords: ["herbal capsules Mansehra", "Pure Herbex Mansehra"],
  },
  {
    slug: "haripur",
    name: "Haripur",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Khanpur", "Ghazi", "Abbottabad", "Islamabad"],
    seoKeywords: ["Pure Herbex Haripur", "herbal delivery Haripur"],
  },
  {
    slug: "dera-ismail-khan",
    name: "Dera Ismail Khan",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "4 business days",
    tier: 3,
    nearbyAreas: ["Kulachi", "Paharpur", "Tank", "Mianwali"],
    seoKeywords: ["herbal stamina DI Khan", "Pure Herbex Dera Ismail Khan"],
  },
  {
    slug: "nowshera",
    name: "Nowshera",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "2–3 business days",
    tier: 2,
    nearbyAreas: ["Jehangira", "Risalpur", "Peshawar", "Charsadda"],
    seoKeywords: ["Pure Herbex Nowshera", "COD Nowshera herbal"],
  },
  {
    slug: "charsadda",
    name: "Charsadda",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Tangi", "Shabqadar", "Mardan", "Peshawar"],
    seoKeywords: ["herbal medicine Charsadda", "Pure Herbex Charsadda"],
  },
  {
    slug: "swabi",
    name: "Swabi",
    province: "Khyber Pakhtunkhwa",
    provinceSlug: "khyber-pakhtunkhwa",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Topi", "Lahor", "Mardan", "Nowshera"],
    seoKeywords: ["Pure Herbex Swabi", "herbal stamina Swabi"],
  },

  // —— Balochistan ——
  {
    slug: "quetta",
    name: "Quetta",
    province: "Balochistan",
    provinceSlug: "balochistan",
    deliveryDays: "4–5 business days",
    tier: 3,
    nearbyAreas: ["Sariab", "Hazara Town", "Kuchlak", "Pishin"],
    localNote:
      "Quetta deliveries use extended courier routes from Punjab. Every parcel remains plain-packaged with COD — no advance payment.",
    seoKeywords: ["herbal stamina Quetta", "Pure Herbex Quetta COD", "timing medicine Quetta"],
  },
  {
    slug: "turbat",
    name: "Turbat",
    province: "Balochistan",
    provinceSlug: "balochistan",
    deliveryDays: "5–6 business days",
    tier: 4,
    nearbyAreas: ["Kech", "Mand", "Gwadar", "Panjgur"],
    seoKeywords: ["Pure Herbex Turbat", "herbal delivery Turbat"],
  },
  {
    slug: "gwadar",
    name: "Gwadar",
    province: "Balochistan",
    provinceSlug: "balochistan",
    deliveryDays: "5–6 business days",
    tier: 4,
    nearbyAreas: ["Pasni", "Ormara", "Turbat", "Hub"],
    seoKeywords: ["herbal capsules Gwadar", "Pure Herbex Gwadar"],
  },
  {
    slug: "khuzdar",
    name: "Khuzdar",
    province: "Balochistan",
    provinceSlug: "balochistan",
    deliveryDays: "4–5 business days",
    tier: 3,
    nearbyAreas: ["Wadh", "Nal", "Kalat", "Lasbela"],
    seoKeywords: ["Pure Herbex Khuzdar", "COD Khuzdar herbal"],
  },
  {
    slug: "hub",
    name: "Hub",
    province: "Balochistan",
    provinceSlug: "balochistan",
    deliveryDays: "3–4 business days",
    tier: 2,
    nearbyAreas: ["Gadani", "Winder", "Karachi", "Lasbela"],
    seoKeywords: ["herbal delivery Hub Chowki", "Pure Herbex Hub"],
  },
  {
    slug: "sibi",
    name: "Sibi",
    province: "Balochistan",
    provinceSlug: "balochistan",
    deliveryDays: "4–5 business days",
    tier: 3,
    nearbyAreas: ["Harnai", "Dhadar", "Quetta", "Jacobabad"],
    seoKeywords: ["Pure Herbex Sibi", "herbal stamina Sibi"],
  },
  {
    slug: "loralai",
    name: "Loralai",
    province: "Balochistan",
    provinceSlug: "balochistan",
    deliveryDays: "5 business days",
    tier: 4,
    nearbyAreas: ["Barkhan", "Musakhel", "Zhob", "Quetta"],
    seoKeywords: ["herbal medicine Loralai", "Pure Herbex Loralai"],
  },

  // —— Gilgit-Baltistan ——
  {
    slug: "gilgit",
    name: "Gilgit",
    province: "Gilgit-Baltistan",
    provinceSlug: "gilgit-baltistan",
    deliveryDays: "4–5 business days",
    tier: 3,
    nearbyAreas: ["Jutial", "Naltar", "Skardu", "Hunza"],
    seoKeywords: ["Pure Herbex Gilgit", "herbal delivery Gilgit Baltistan"],
  },
  {
    slug: "skardu",
    name: "Skardu",
    province: "Gilgit-Baltistan",
    provinceSlug: "gilgit-baltistan",
    deliveryDays: "5–6 business days",
    tier: 4,
    nearbyAreas: ["Shigar", "Khaplu", "Gilgit", "Astore"],
    seoKeywords: ["herbal stamina Skardu", "Pure Herbex Skardu COD"],
  },
  {
    slug: "hunza",
    name: "Hunza",
    province: "Gilgit-Baltistan",
    provinceSlug: "gilgit-baltistan",
    deliveryDays: "5–6 business days",
    tier: 4,
    nearbyAreas: ["Aliabad", "Karimabad", "Gilgit", "Nagar"],
    seoKeywords: ["Pure Herbex Hunza", "herbal capsules Hunza Valley"],
  },

  // —— Azad Kashmir ——
  {
    slug: "muzaffarabad",
    name: "Muzaffarabad",
    province: "Azad Jammu & Kashmir",
    provinceSlug: "azad-kashmir",
    deliveryDays: "3–4 business days",
    tier: 3,
    nearbyAreas: ["Chattar", "Garhi Dupatta", "Rawalakot", "Hattian"],
    seoKeywords: ["herbal medicine Muzaffarabad", "Pure Herbex AJK delivery"],
  },
  {
    slug: "mirpur-ajk",
    name: "Mirpur (AJK)",
    province: "Azad Jammu & Kashmir",
    provinceSlug: "azad-kashmir",
    deliveryDays: "3 business days",
    tier: 2,
    nearbyAreas: ["Dadyal", "Kotli", "Bhimber", "Jhelum"],
    seoKeywords: ["Pure Herbex Mirpur AJK", "herbal stamina Mirpur Kashmir"],
  },
  {
    slug: "kotli",
    name: "Kotli",
    province: "Azad Jammu & Kashmir",
    provinceSlug: "azad-kashmir",
    deliveryDays: "4 business days",
    tier: 3,
    nearbyAreas: ["Sehnsa", "Charhoi", "Mirpur", "Rawalakot"],
    seoKeywords: ["herbal COD Kotli AJK", "Pure Herbex Kotli"],
  },
  {
    slug: "rawalakot",
    name: "Rawalakot",
    province: "Azad Jammu & Kashmir",
    provinceSlug: "azad-kashmir",
    deliveryDays: "4 business days",
    tier: 3,
    nearbyAreas: ["Pallandri", "Bagh", "Muzaffarabad", "Kotli"],
    seoKeywords: ["Pure Herbex Rawalakot", "herbal delivery Rawalakot"],
  },
  {
    slug: "bhimber",
    name: "Bhimber",
    province: "Azad Jammu & Kashmir",
    provinceSlug: "azad-kashmir",
    deliveryDays: "3–4 business days",
    tier: 3,
    nearbyAreas: ["Samahni", "Mirpur", "Gujrat", "Kotli"],
    seoKeywords: ["herbal capsules Bhimber", "Pure Herbex Bhimber"],
  },
];

export function getCityBySlug(slug: string): DeliveryCity | undefined {
  return deliveryCities.find((c) => c.slug === slug);
}

export function getCitiesByProvince(provinceSlug: string): DeliveryCity[] {
  return deliveryCities.filter((c) => c.provinceSlug === provinceSlug);
}

export function getNearbyCityLinks(city: DeliveryCity, limit = 6): DeliveryCity[] {
  const sameProvince = deliveryCities.filter(
    (c) => c.provinceSlug === city.provinceSlug && c.slug !== city.slug
  );
  const others = deliveryCities.filter(
    (c) => c.provinceSlug !== city.provinceSlug && c.slug !== city.slug
  );
  return [...sameProvince, ...others].slice(0, limit);
}

export function getWhatsAppOrderLink(cityName: string): string {
  const text = encodeURIComponent(
    `Assalam o Alaikum, I want to order Pure Herbex Ultra Force (Rs. 3,000 COD) for delivery in ${cityName}.`
  );
  return `https://wa.me/923160924151?text=${text}`;
}
