export type Ingredient = {
  slug: string;
  name: string;
  urduName: string;
  latinName: string;
  category: "Adaptogen" | "Mineral" | "Aphrodisiac" | "Vasodilator" | "Tonic" | "Antioxidant";
  benefit: string;
  excerpt: string;
  description: string;
  benefits: string[];
  seoKeywords: string[];
  relatedSlugs: string[];
  image?: string;
};

const img = (file: string) => `/assets/images/ingredients/${file}`;

export const ingredients: Ingredient[] = [
  {
    slug: "ashwagandha",
    name: "Ashwagandha",
    urduName: "اشوگندھا",
    latinName: "Withania somnifera",
    category: "Adaptogen",
    benefit: "Cortisol reduction & stamina boost",
    excerpt: "Premier Ayurvedic adaptogen for stress, testosterone support, and physical endurance.",
    description:
      "Ashwagandha is clinically studied for lowering cortisol and supporting natural testosterone in men under chronic stress — a common barrier to stamina in Pakistan's high-pressure urban lifestyles.",
    benefits: ["Reduces cortisol up to 30% in trials", "Supports muscle strength and VO2 max", "Calms performance anxiety via GABA pathways", "Foundational herb in Ultra Force daily protocol"],
    seoKeywords: ["Ashwagandha benefits men Pakistan", "اشوگندھا فوائد", "herbal testosterone support"],
    relatedSlugs: ["shilajit", "tribulus-terrestris", "safed-musli"],
    image: img("ashwagandha.png"),
  },
  {
    slug: "shilajit",
    name: "Shilajit (Salajeet)",
    urduName: "سلاجیت",
    latinName: "Asphaltum punjabianum",
    category: "Mineral",
    benefit: "Fulvic acid & 84+ trace minerals",
    excerpt: "Himalayan mineral resin for ATP energy, testosterone, and cellular vitality.",
    description:
      "Gold-grade purified Shilajit delivers fulvic acid and ionic minerals that restore deep stamina at the mitochondrial level — the biological foundation of Pure Herbex Ultra Force.",
    benefits: ["Enhances ATP and mitochondrial output", "Supports free testosterone in clinical data", "Improves nutrient absorption of co-herbs", "Purified 7-stage for heavy-metal safety"],
    seoKeywords: ["Salajeet benefits Pakistan", "original Shilajit", "سلاجیت فوائد"],
    relatedSlugs: ["ashwagandha", "tribulus-terrestris", "korean-ginseng"],
  },
  {
    slug: "tribulus-terrestris",
    name: "Tribulus Terrestris",
    urduName: "گکھرو",
    latinName: "Tribulus terrestris",
    category: "Vasodilator",
    benefit: "LH support & natural vasodilation",
    excerpt: "Gokshura — world's most researched botanical for luteinizing hormone and vascular fullness.",
    description:
      "Tribulus contains protodioscin, which supports luteinizing hormone signalling and natural nitric oxide pathways for hardness and vascular health without chemical PDE5 force.",
    benefits: ["Supports natural testosterone signalling", "Promotes corpus cavernosum blood capacity", "Used for centuries in Unani virility tonics", "Synergises with Saffron and Musli"],
    seoKeywords: ["Gokshura Pakistan", "Tribulus benefits men", "گکھرو فوائد"],
    relatedSlugs: ["safed-musli", "saffron", "shilajit"],
  },
  {
    slug: "safed-musli",
    name: "Safed Musli (Musli Sufaid)",
    urduName: "موسلی سفید",
    latinName: "Chlorophytum borivilianum",
    category: "Tonic",
    benefit: "Reproductive vitality & volume",
    excerpt: "Classical 'herbal Viagra' of Ayurveda for sperm quality, drive, and recovery.",
    description:
      "Safed Musli is prized for improving seminal parameters, reducing fatigue, and supporting long-session stamina — a core pillar of male reproductive wellness in South Asian pharmacopoeia.",
    benefits: ["Supports sperm count and motility markers", "Reduces post-exertion fatigue", "Adaptogenic tonic for daily use", "Pairs with Tribulus for vascular synergy"],
    seoKeywords: ["Musli Sufaid benefits", "موسلی سفید", "natural stamina herb Pakistan"],
    relatedSlugs: ["tribulus-terrestris", "ashwagandha", "kaunch-beej"],
    image: img("musli-sufaid.png"),
  },
  {
    slug: "saffron",
    name: "Pure Saffron (Zafran)",
    urduName: "زعفران",
    latinName: "Crocus sativus",
    category: "Aphrodisiac",
    benefit: "Libido & mood-linked circulation",
    excerpt: "Premium Zafran for performance anxiety, mood, and micro-circulation.",
    description:
      "Medical literature links saffron to improved arousal markers and reduced performance anxiety — critical for men whose stamina issues are partly psychological.",
    benefits: ["Mood stabilisation for performance confidence", "Triggers healthy peripheral circulation", "Potent antioxidant for vascular tissue", "Used in royal Unani formulations"],
    seoKeywords: ["Zafran benefits men", "زعفران فوائد", "saffron libido Pakistan"],
    relatedSlugs: ["nutmeg", "tribulus-terrestris", "ashwagandha"],
    image: img("saffron.png"),
  },
  {
    slug: "korean-ginseng",
    name: "Korean Ginseng",
    urduName: "جنسنگ",
    latinName: "Panax ginseng",
    category: "Adaptogen",
    benefit: "Vitality & blood-flow optimisation",
    excerpt: "Panax ginseng for alert stamina, cardiovascular efficiency, and daily drive.",
    description:
      "Korean Ginseng improves perceived energy and cardiovascular response — supporting men who need all-day vitality before intimate performance.",
    benefits: ["Improves perceived energy and focus", "Supports cardiovascular efficiency", "Complements Shilajit mineral base", "Standardised extract for consistent dosing"],
    seoKeywords: ["Korean Ginseng stamina Pakistan", "جنسنگ فوائد", "ginseng male health"],
    relatedSlugs: ["shilajit", "ashwagandha", "vidarikand"],
    image: img("gensing.png"),
  },
  {
    slug: "nutmeg",
    name: "Nutmeg (Jaiphal)",
    urduName: "جائفل",
    latinName: "Myristica fragrans",
    category: "Aphrodisiac",
    benefit: "Traditional timing support",
    excerpt: "Jaiphal — classical spice for warmth, sensitivity balance, and duration.",
    description:
      "Nutmeg has a long Subcontinental tradition for male timing and warmth. In Ultra Force it is precisely dosed within a balanced 32-herb matrix — never as a standalone stimulant.",
    benefits: ["Traditional timing and warmth support", "Aromatic circulatory stimulation", "Balanced dose within full formula", "Works with Laung and Dalchini"],
    seoKeywords: ["Jaiphal benefits men", "جائفل", "nutmeg herbal timing"],
    relatedSlugs: ["saffron", "lajwanti", "clove"],
    image: img("nutmeg.png"),
  },
  {
    slug: "lajwanti",
    name: "Lajwanti",
    urduName: "لجونتی",
    latinName: "Mimosa pudica",
    category: "Tonic",
    benefit: "Sensitivity & control support",
    excerpt: "Traditional herb for neuromuscular composure and sensitivity balance.",
    description:
      "Lajwanti appears in classical Unani texts for men seeking better control and reduced hypersensitivity — supporting confidence without numbing agents.",
    benefits: ["Traditional sensitivity modulation", "Supports neuromuscular composure", "Non-synthetic control pathway", "Combined with Jaiphal in formula"],
    seoKeywords: ["Lajwanti herb benefits", "لجونتی", "timing control herbal"],
    relatedSlugs: ["nutmeg", "akarkara", "clove"],
    image: img("lajwanti.png"),
  },
  {
    slug: "kaunch-beej",
    name: "Kaunch Beej",
    urduName: "کونچ بیج",
    latinName: "Mucuna pruriens",
    category: "Tonic",
    benefit: "Dopamine & drive support",
    excerpt: "Velvet bean seed — natural L-DOPA precursor for drive and mood.",
    description:
      "Kaunch Beej naturally contains L-DOPA precursors supporting dopamine pathways linked to motivation, drive, and pleasure response.",
    benefits: ["Supports dopamine-linked drive", "Traditional nerve tonic", "Pairs with Ashwagandha adaptogen stack", "Helps combat stress-related apathy"],
    seoKeywords: ["Kaunch Beej benefits", "کونچ بیج", "Mucuna pruriens Pakistan"],
    relatedSlugs: ["ashwagandha", "safed-musli", "shatavari"],
  },
  {
    slug: "akarkara",
    name: "Akarkara",
    urduName: "اکرکرا",
    latinName: "Anacyclus pyrethrum",
    category: "Vasodilator",
    benefit: "Local circulation & response",
    excerpt: "Sharp warming herb for peripheral blood flow and neural response.",
    description:
      "Akarkara is used in Unani medicine to stimulate local circulation and neural responsiveness — supporting the 'awakening' phase of natural performance.",
    benefits: ["Stimulates local blood flow", "Traditional neural invigorant", "Warming counterbalance to adaptogens", "Micro-dosed in full matrix"],
    seoKeywords: ["Akarkara benefits men", "اکرکرا", "Unani virility herb"],
    relatedSlugs: ["tribulus-terrestris", "saffron", "black-pepper"],
  },
  {
    slug: "salab-misri",
    name: "Salab Misri",
    urduName: "ثعلب مصری",
    latinName: "Orchis mascula",
    category: "Tonic",
    benefit: "Classical virility orchid tuber",
    excerpt: "Rare orchid tuber from Unani tradition for youthfulness and vigour.",
    description:
      "Salab Misri is a prized Unani ingredient historically reserved for royal stamina tonics — included in Ultra Force for holistic reproductive nourishment.",
    benefits: ["Classical virility restorative", "Nutritive tuber polysaccharides", "Synergy with Musli and Shatavari", "Heritage Unani credibility"],
    seoKeywords: ["Salab Misri benefits", "ثعلب مصری", "Unani stamina herb"],
    relatedSlugs: ["safed-musli", "shatavari", "vidarikand"],
  },
  {
    slug: "vidarikand",
    name: "Vidarikand",
    urduName: "ویداری کند",
    latinName: "Pueraria tuberosa",
    category: "Tonic",
    benefit: "Strength & recovery tuber",
    excerpt: "Ayurvedic tuber for physical recovery, nourishment, and endurance.",
    description:
      "Vidarikand supports tissue nourishment and recovery — helping men who feel physically depleted before intimate activity.",
    benefits: ["Supports tissue nourishment", "Aids physical recovery", "Complements Ginseng energy stack", "Traditional strength tuber"],
    seoKeywords: ["Vidarikand benefits", "ویداری کند", "herbal recovery Pakistan"],
    relatedSlugs: ["korean-ginseng", "ashwagandha", "amla"],
  },
  {
    slug: "shatavari",
    name: "Shatavari",
    urduName: "شاتاوری",
    latinName: "Asparagus racemosus",
    category: "Tonic",
    benefit: "Reproductive system nourishment",
    excerpt: "Cooling nutritive adaptogen balancing heat-producing virility herbs.",
    description:
      "Shatavari provides cooling nutritive balance to the warming virility herbs — supporting long-term reproductive system health without overheating the body.",
    benefits: ["Reproductive system nourishment", "Cooling balance to warming herbs", "Supports mucosal and fluid health", "Ayurvedic rasayana partner"],
    seoKeywords: ["Shatavari men benefits", "شاتاوری", "herbal balance formula"],
    relatedSlugs: ["safed-musli", "salab-misri", "amla"],
  },
  {
    slug: "amla",
    name: "Amla",
    urduName: "آملہ",
    latinName: "Phyllanthus emblica",
    category: "Antioxidant",
    benefit: "Vitamin C & vascular protection",
    excerpt: "Potent antioxidant protecting blood vessels from oxidative damage.",
    description:
      "Amla is one of nature's richest vitamin C sources — protecting delicate vascular tissues and supporting collagen integrity in performance-critical circulation.",
    benefits: ["Powerful vascular antioxidant", "Supports collagen and vessel health", "Enhances iron and mineral utilisation", "Protects long-term nitric oxide pathways"],
    seoKeywords: ["Amla benefits men", "آملہ فوائد", "antioxidant stamina"],
    relatedSlugs: ["shilajit", "tribulus-terrestris", "shatavari"],
  },
  {
    slug: "clove",
    name: "Clove (Laung)",
    urduName: "لونگ",
    latinName: "Syzygium aromaticum",
    category: "Vasodilator",
    benefit: "Warmth & micro-circulation",
    excerpt: "Laung — warming spice stimulating peripheral blood flow.",
    description:
      "Clove provides eugenol-driven warming micro-circulation — a classical companion to Jaiphal and Dalchini in Subcontinental virility preparations.",
    benefits: ["Eugenol micro-circulation support", "Warming aromatic stimulus", "Antimicrobial gut support", "Traditional timing spice trio"],
    seoKeywords: ["Laung benefits men", "لونگ", "clove herbal stamina"],
    relatedSlugs: ["nutmeg", "cinnamon", "black-pepper"],
  },
  {
    slug: "cinnamon",
    name: "Cinnamon (Dalchini)",
    urduName: "دار چینی",
    latinName: "Cinnamomum cassia",
    category: "Vasodilator",
    benefit: "Blood sugar & warmth balance",
    excerpt: "Dalchini supports metabolic balance and gentle vasodilation.",
    description:
      "Cinnamon supports insulin sensitivity and gentle vasodilation — important for men whose performance is affected by blood sugar swings and metabolic stress.",
    benefits: ["Metabolic and glucose balance", "Gentle vasodilatory warmth", "Antioxidant polyphenols", "Balances spice heat in formula"],
    seoKeywords: ["Dalchini benefits", "دار چینی", "cinnamon blood flow"],
    relatedSlugs: ["clove", "nutmeg", "black-pepper"],
  },
  {
    slug: "black-pepper",
    name: "Black Pepper (Filfil Siah)",
    urduName: "کالی مرچ",
    latinName: "Piper nigrum",
    category: "Tonic",
    benefit: "Bioavailability enhancer",
    excerpt: "Piperine boosts absorption of co-herbs across the formula.",
    description:
      "Black pepper's piperine is the classical bio-enhancer — increasing absorption of Ashwagandha, Curcumin-class compounds, and mineral complexes throughout Ultra Force.",
    benefits: ["Piperine absorption enhancement", "Thermogenic circulation support", "Ayurvedic bioavailability partner", "Activates dormant co-nutrients"],
    seoKeywords: ["Piperine herbal absorption", "کالی مرچ", "black pepper supplement synergy"],
    relatedSlugs: ["ashwagandha", "shilajit", "akarkara"],
  },
  {
    slug: "mace",
    name: "Mace (Bisbasa)",
    urduName: "بسباسہ",
    latinName: "Myristica fragrans",
    category: "Aphrodisiac",
    benefit: "Nutmeg companion aromatic",
    excerpt: "Bisbasa — aromatic aril supporting Jaiphal's warming profile.",
    description:
      "Mace shares nutmeg's myristicin profile with a finer aromatic signature — doubling the traditional Jaiphal warming axis in controlled doses.",
    benefits: ["Aromatic warming support", "Complements Jaiphal profile", "Traditional aphrodisiac spice", "Micro-dosed for safety"],
    seoKeywords: ["Bisbasa herb", "بسباسہ", "mace nutmeg stamina"],
    relatedSlugs: ["nutmeg", "clove", "saffron"],
  },
  {
    slug: "jawatri",
    name: "Jawatri",
    urduName: "جاوتری",
    latinName: "Myristica fragrans",
    category: "Aphrodisiac",
    benefit: "Aromatic virility spice",
    excerpt: "Sister spice to Jaiphal in classical timing preparations.",
    description:
      "Jawatri completes the nutmeg-mace aromatic axis used across Mughal-era stamina tonics — present in Ultra Force for heritage-complete spice synergy.",
    benefits: ["Completes nutmeg spice axis", "Aromatic circulatory warmth", "Heritage Mughal formulation note", "Synergy not standalone dosing"],
    seoKeywords: ["Jawatri benefits", "جاوتری", "Unani spice formula"],
    relatedSlugs: ["nutmeg", "mace", "clove"],
  },
  {
    slug: "rock-sugar",
    name: "Rock Sugar (Misri)",
    urduName: "مشری",
    latinName: "Crystallised sucrose",
    category: "Tonic",
    benefit: "Classical carrier & cooling base",
    excerpt: "Misri — traditional Unani carrier balancing herb heat.",
    description:
      "Rock sugar acts as a classical Unani harmoniser — moderating herb heat and supporting palatability in traditional decoction logic adapted to capsule delivery.",
    benefits: ["Harmonises warming herb profile", "Traditional Unani excipient logic", "Gentle energy substrate", "Balances pungent spice notes"],
    seoKeywords: ["Misri Unani", "مشری", "herbal formula balance"],
    relatedSlugs: ["shatavari", "amla", "tamarind"],
  },
  {
    slug: "suranjan",
    name: "Suranjan",
    urduName: "سورنجان",
    latinName: "Colchicum luteum",
    category: "Tonic",
    benefit: "Joint & mobility support",
    excerpt: "Traditional herb for physical comfort and confident movement.",
    description:
      "Suranjan is included for men whose physical stiffness and joint discomfort limit confidence and stamina — supporting comfortable, unrestricted movement.",
    benefits: ["Traditional joint comfort support", "Improves physical confidence", "Unani mobility herb", "Supports active lifestyle"],
    seoKeywords: ["Suranjan benefits", "سورنجان", "herbal joint stamina"],
    relatedSlugs: ["ashwagandha", "shilajit", "vidarikand"],
  },
  {
    slug: "tamarind",
    name: "Tamarind (Imli)",
    urduName: "املی",
    latinName: "Tamarindus indica",
    category: "Antioxidant",
    benefit: "Digestive & cooling balance",
    excerpt: "Imli — digestive harmoniser in heavy herbal matrices.",
    description:
      "Tamarind provides organic acids and cooling digestive balance — helping the body tolerate a dense 32-herb matrix without gastric burden.",
    benefits: ["Digestive harmonisation", "Cooling counter to warming herbs", "Polyphenol antioxidant support", "Traditional digestive adjuvant"],
    seoKeywords: ["Imli herbal digestion", "املی", "tamarind supplement balance"],
    relatedSlugs: ["amla", "rock-sugar", "black-pepper"],
  },
  {
    slug: "aloe-vera",
    name: "Aloe Vera",
    urduName: "ایلو ویرا",
    latinName: "Aloe barbadensis",
    category: "Tonic",
    benefit: "Cooling & gut lining support",
    excerpt: "Soothes gastric lining while dense herbs metabolise.",
    description:
      "Aloe supports gastric comfort during long-term herbal supplementation — protecting the gut lining while adaptogens and minerals process.",
    benefits: ["Gastric lining comfort", "Cooling mucilaginous support", "Long-term tolerance aid", "Pairs with Tamarind digestion stack"],
    seoKeywords: ["Aloe Vera men's health", "ایلو ویرا", "herbal gut support"],
    relatedSlugs: ["tamarind", "shatavari", "amla"],
  },
  {
    slug: "podina",
    name: "Mint (Podina)",
    urduName: "پودینہ",
    latinName: "Mentha piperita",
    category: "Tonic",
    benefit: "Digestive & fresh circulatory note",
    excerpt: "Podina — cooling digestive finish to the formula.",
    description:
      "Mint provides a cooling digestive finish and mild vasodilatory freshness — preventing the heavy warming profile from overwhelming sensitive users.",
    benefits: ["Cooling digestive finish", "Mild vasodilatory freshness", "Palatability in capsule matrix", "Traditional stomach calmative"],
    seoKeywords: ["Podina herbal benefits", "پودینہ", "mint digestion supplement"],
    relatedSlugs: ["aloe-vera", "tamarind", "clove"],
  },
  {
    slug: "salam-mishri",
    name: "Salam Mishri",
    urduName: "سلام مشری",
    latinName: "Orchis latifolia",
    category: "Tonic",
    benefit: "Orchid nutritive tonic",
    excerpt: "Rare orchid nutritive paired with Salab Misri tradition.",
    description:
      "Salam Mishri continues the orchid-tuber nutritive axis in Unani pharmacy — supporting fluid balance and reproductive nourishment.",
    benefits: ["Orchid nutritive polysaccharides", "Fluid and nourishment support", "Pairs with Salab Misri axis", "Heritage tonic credibility"],
    seoKeywords: ["Salam Mishri benefits", "سلام مشری", "Unani orchid herb"],
    relatedSlugs: ["salab-misri", "shatavari", "safed-musli"],
  },
  {
    slug: "waj-turki",
    name: "Waj Turki",
    urduName: "وج ترکی",
    latinName: "Acorus calamus",
    category: "Tonic",
    benefit: "Nerve & digestive tonic",
    excerpt: "Classical nerve tonic supporting composure and digestion.",
    description:
      "Waj Turki is a classical nerve and digestive tonic in Eastern pharmacy — supporting the calm focus needed for confident performance.",
    benefits: ["Nerve composure support", "Digestive tonic heritage", "Calm focus for performance", "Balances stimulant spices"],
    seoKeywords: ["Waj Turki Unani", "وج ترکی", "herbal nerve tonic"],
    relatedSlugs: ["ashwagandha", "lajwanti", "podina"],
  },
  {
    slug: "kushta-qalai",
    name: "Kushta Qalai",
    urduName: "کشتہ قلیعی",
    latinName: "Processed tin calx",
    category: "Mineral",
    benefit: "Unani mineral calx tradition",
    excerpt: "Traditional processed mineral in precise Unani calx form.",
    description:
      "Kushta Qalai represents the mineral calx tradition in Unani medicine — included in micro-processed form within modern safety standards of Ultra Force.",
    benefits: ["Unani mineral calx heritage", "Micro-processed modern safety", "Mineral axis with Shilajit", "Classical formulation authenticity"],
    seoKeywords: ["Kushta Qalai Unani", "کشتہ قلیعی", "mineral stamina tonic"],
    relatedSlugs: ["shilajit", "rock-sugar", "black-pepper"],
  },
  {
    slug: "qust-sheereen",
    name: "Qust Sheereen",
    urduName: "قسط شیریں",
    latinName: "Saussurea costus",
    category: "Tonic",
    benefit: "Aromatic digestive & warmth",
    excerpt: "Sweet costus — aromatic digestive in prophetic medicine tradition.",
    description:
      "Qust Sheereen is revered in traditional medicine for digestive warmth and aromatic balance — supporting men with sluggish digestion affecting vitality.",
    benefits: ["Aromatic digestive warmth", "Prophetic medicine heritage", "Supports sluggish gut vitality", "Balances cooling herbs"],
    seoKeywords: ["Qust Sheereen benefits", "قسط شیریں", "costus herbal"],
    relatedSlugs: ["clove", "cinnamon", "black-pepper"],
  },
  {
    slug: "beej-bhang",
    name: "Beej Bhang",
    urduName: "بیج بھنگ",
    latinName: "Cannabis sativa seed",
    category: "Tonic",
    benefit: "Seed oil nutritive (non-psychoactive)",
    excerpt: "Hemp seed nutritive — fatty acids for hormone synthesis support.",
    description:
      "Ultra Force uses hemp seed (non-psychoactive) for essential fatty acids supporting hormone synthesis and cellular membrane health — not leaf or resin.",
    benefits: ["Essential fatty acid profile", "Hormone synthesis substrate", "Non-psychoactive seed only", "Membrane health support"],
    seoKeywords: ["hemp seed men's health", "بیج بھنگ", "essential fats stamina"],
    relatedSlugs: ["kaunch-beej", "shilajit", "vidarikand"],
  },
  {
    slug: "konch-beej",
    name: "Konch Beej",
    urduName: "کونچ بیج",
    latinName: "Mucuna pruriens",
    category: "Tonic",
    benefit: "Nerve & reproductive seed",
    excerpt: "Variant velvet bean profile for nerve-reproductive axis.",
    description:
      "Konch Beej reinforces the Mucuna axis with a complementary seed profile targeting nerve endurance and reproductive fluid health in Unani dosing logic.",
    benefits: ["Nerve endurance support", "Reproductive fluid axis", "Complements Kaunch Beej", "Traditional seed tonic"],
    seoKeywords: ["Konch Beej benefits", "کونچ بیج", "velvet bean Pakistan"],
    relatedSlugs: ["kaunch-beej", "safed-musli", "salam-mishri"],
  },
  {
    slug: "gokhru",
    name: "Gokhru",
    urduName: "گوکھرو",
    latinName: "Tribulus terrestris",
    category: "Vasodilator",
    benefit: "Kidney & urinary tract support",
    excerpt: "Complementary Gokhru profile for renal vitality axis.",
    description:
      "Gokhru supports renal and urinary tract wellness — traditionally linked to male vitality in Ayurveda when kidney energy (Vajikarana context) is depleted.",
    benefits: ["Renal vitality traditional support", "Urinary tract wellness", "Complements Tribulus axis", "Ayurvedic Vajikarana context"],
    seoKeywords: ["Gokhru benefits men", "گوکھرو", "kidney vitality herb"],
    relatedSlugs: ["tribulus-terrestris", "shilajit", "amla"],
  },
  {
    slug: "zafran-extract",
    name: "Zafran Extract (Concentrated)",
    urduName: "زعفران عرق",
    latinName: "Crocus sativus extract",
    category: "Aphrodisiac",
    benefit: "Concentrated saffron actives",
    excerpt: "Standardised saffron extract for consistent crocin & safranal levels.",
    description:
      "Beyond raw saffron threads, concentrated Zafran extract ensures consistent crocin and safranal levels batch-to-batch — critical for reliable mood-circulation benefits.",
    benefits: ["Standardised crocin/safranal", "Batch-to-batch consistency", "Mood-circulation reliability", "Premium extract grade"],
    seoKeywords: ["Zafran extract benefits", "زعفران عرق", "saffron extract men"],
    relatedSlugs: ["saffron", "nutmeg", "tribulus-terrestris"],
  },
];

export function getIngredientBySlug(slug: string): Ingredient | undefined {
  return ingredients.find((i) => i.slug === slug);
}

export function getRelatedIngredients(ingredient: Ingredient, limit = 4): Ingredient[] {
  return ingredient.relatedSlugs
    .map((s) => getIngredientBySlug(s))
    .filter((i): i is Ingredient => !!i)
    .slice(0, limit);
}
